[package]
name = "blockchain-lab"
version = "0.1.0"
authors = ["Dong Zhou <dong.zhou.08@gmail.com>"]

[dependencies]
clap = "2"
term_size = "0.3"
textwrap = "0.9"
toml = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
parity-version = { path = "util/version" }
panic_hook = { path = "util/panic_hook" }
dir = { path = "util/dir" }
ethcore-crypto = { path = "crypto" }
ethkey = { path = "ethkey" }