[package]
name = "rpc"
version = "0.1.0"
authors = ["Dong Zhou <dongz@conflux-chain.org>"]
edition = "2018"

[dependencies]
ethereum-types = "0.4"
rustc-hex = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

core = { path = "../core" }
primitives = { path = "../primitives" }
