[package]
description = "Conflux core library"
homepage = "http://www.conflux-chain.io"
license = "GPL-3.0"
name = "core"
version = "0.1.0"
authors = ["ming wu <ming@alt-chain.io>"]

[dependencies]
keccak-hash = { git = "https://github.com/paritytech/parity-common" }
ethereum-types = "0.3"
common-types = { path = "types" }
parity-bytes = { git = "https://github.com/paritytech/parity-common" }
parking_lot = "0.6"
network = { path = "../network" }
ethcore-io = { path = "../util/io" }
log = "0.3"
rlp = { git = "https://github.com/paritytech/parity-common" }
