[package]
name = "kvdb"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
elastic-array = "0.10"
error-chain = { version = "0.11", default-features = false }
ethcore-bytes = { path = "../bytes" }
