[package]
name = "util-error"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
rlp = { path = "../rlp" }
kvdb = { path = "../kvdb" }
ethereum-types = "0.4"
error-chain = { version = "0.11", default-features = false }
rustc-hex = "1.0"
