#!/usr/bin/env python3
from test_node import TestNode
from time import sleep

x = TestNode(0, "/tmp", "127.0.0.1", 31001, 32001, 33001, "../../target/debug/conflux")
y = TestNode(1, "/tmp", "127.0.0.1", 31002, 32002, 33002, "../../target/debug/conflux")
x.start()
y.start()
x.wait_for_rpc_connection()
y.wait_for_rpc_connection()
print(x.get_block_count())
x.generate(1)
print(x.get_block_count())
x.generate(2)
print(x.get_block_count())
x.generate(3)
print(x.get_block_count())
print(x.get_best_block_hash())
print(y.get_block_count())
print(y.get_best_block_hash())
x.add_peer("127.0.0.1:31002")
sleep(5)
print("After sleep!")
print(y.get_block_count())
print(y.get_best_block_hash())
