[package]
name = "message"
version = "0.1.0"
authors = ["Dong Zhou <dongz@conflux-chain.org>"]
edition = "2018"

[dependencies]
rlp = { git = "https://github.com/paritytech/parity-common" }
ethereum-types = "0.4"
ethcore-bytes = "0.1.1"
primitives = { path = "../primitives" }
log = "0.3"
