[package]
description = "Conflux executor library"
homepage = "http://www.conflux-chain.io"
license = "GPL-3.0"
name = "executor"
version = "0.1.0"
authors = ["ming wu <ming@alt-chain.io>"]

[dependencies]
